name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    strategy:
      matrix:
        node: ["24.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-npm-cache-

      - name: Install
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
